import Head from 'next/head'
import Image from 'next/image'
import { Button, Htag, P, Tag } from '../components';
import styles from '../styles/Home.module.css'
// import { Inter } from '@next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export default function Home():JSX.Element {
  const a = 1;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className={styles.main}>
        <Htag tag={"h1"}>Text</Htag>
        <Button appearance="primary" arrow="right">
          Кнопка
        </Button>
        <Button appearance="ghost" arrow="down">
          Кнопка
        </Button>
        <P size="l">Text</P>
        <Tag size="s" color="red">
          Red
        </Tag>
        <Tag size="s" color="green">
          green
        </Tag>
        <Tag size="m" color="grey">
          grey
        </Tag>
        <Tag size="s" color="grey" href="#">
          grey
        </Tag>
        <Tag size="s" color="primary" href="#">
          primary
        </Tag>
        
      </main>
    </>
  );
}
